name: homzy1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  kommunicate_flutter: ^1.6.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  country_picker: ^2.0.18
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  pinput: ^2.2.16
  image_picker: ^0.8.6
  font_awesome_flutter: ^10.4.0

  carousel_pro: ^1.0.0
  upi_india: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/spa_image.jpg
    - assets/images/spa.png
    - assets/images/massage.png
    - assets/images/cleaning.png
    - assets/images/painting.png
    - assets/images/Repair.png
    - assets/carsoul_image/salon_banner.jpeg
    - assets/salon_men/salon_service_men.jpeg
    - assets/salon_men/men_shaving.jpeg
    - assets/salon_men/men_hair_color.jpeg
    - assets/salon_men/facila_treatment.jpeg
    - assets/salon_women/haircut.jpeg
    - assets/salon_women/hair_color.jpeg
    - assets/salon_women/manicure.webp
    - assets/salon_women/glow.jpeg
    - assets/sub_service/plumber_image/Faucet.jpeg
    - assets/sub_service/plumber_image/piper_repair_2.0.jpeg
    - assets/sub_service/plumber_image/water_heater.png
    - assets/sub_service/Electric_image/ac_repair.jpeg
    - assets/sub_service/Electric_image/Lighting.jpeg
    - assets/sub_service/Electric_image/washing_image.jpg
    - assets/carsoul_image/massage_salon_men.jpeg
    - assets/carsoul_image/plumber_banner.jpeg
    - assets/carsoul_image/electric_banner.jpeg
    - assets/salon_men/child_hari_cut.jpeg
    - assets/salon_men/men_shaving_4.1.jpeg
    - assets/salon_men/men_color_3.3.png
    - assets/salon_men/facila_treatment.jpeg
    - assets/salon_women/manicure_3.1.jpeg
    - assets/salon_women/coloring hair_women_sec.jpeg
    - assets/salon_women/hair_cutt_women_5.2.jpeg
    - assets/salon_women/change_pixel.jpg
    - assets/salon_women/makup_women_3.1.webp
    - assets/sub_service/plumber_image/faucet_4.1.webp
    - assets/sub_service/plumber_image/pipe_4.1.webp
    - assets/sub_service/plumber_image/water_heater.png
    - assets/sub_service/plumber_image/water_purifier.webp
    - assets/sub_service/Electric_image/ac_repair_3.3.jpeg
    - assets/sub_service/Electric_image/washing_machine_3.2.jpeg
    - assets/sub_service/Electric_image/lighting_3.3.webp
    - assets/sub_service/Electric_image/referegator-repairing-large.jpg
    - assets/sub_service/plumber_subscreen.jpeg
    - assets/sub_service/470110063 (1).jpg
    - assets/sub_service/plumber_image/pipe_repair.jpeg
    - assets/sub_service/plumber_image/piper_repair_2.0.jpeg
    - assets/salon_men/men_salon.jpeg
    - assets/salon_men/facial_trement_2.0.webp
    - assets/salon_women/women_haircut_2.0.jpeg
    - assets/sub_service/plumber_image/water_heater_3.3.jpeg
    - assets/sub_service/plumber_image/water_system_3.2.jpeg
    - assets/cleaning_service/bathroom_cleaning.jpeg
    - assets/cleaning_service/kitchen_cleaning.jpeg
    - assets/cleaning_service/sofa_cleaning.jpeg
    - assets/cleaning_service/carpet_cleaning.webp
    - assets/cleaning_service/1_room_set_cleaning.jpeg
    - assets/cleaning_service/garden claening.jpeg
    - assets/cleaning_service/bathroom_cleaning_poster.jpeg
    - assets/cleaning_service/kitchen_cleaner_poster.jpeg
    - assets/cleaning_service/garden_cleaner_poster.jpeg
    - assets/cleaning_service/carpet_cleaner_poster.jpeg
    - assets/cleaning_service/sofa_cleaner_poster.jpeg
    - assets/repair_serivce/switch_repair.jpeg
    - assets/repair_serivce/ovens_stoves_repair.jpeg
    - assets/repair_serivce/vaccum_cleaners.jpeg
    - assets/repair_serivce/fan_repair.webp
    - assets/repair_serivce/electrical-wiring.jpeg
    - assets/repair_serivce/wire_repair_2.3.jpeg
    - assets/repair_serivce/vacuum_poster.jpeg
    - assets/repair_serivce/fan_poster.webp
    - assets/repair_serivce/stove_poster.jpeg
    - assets/repair_serivce/stove_poster_2.1.jpeg
    - assets/repair_serivce/switch_poster.jpeg
    - assets/repair_serivce/electric_main.webp
    - assets/book.png
    -
  #   - images/a_dot_ham.jpe
